<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
Перемножение матриц
Напишите две функции, каждая из которых перемножает две квадратные матрицы: одна без использования встроенных функций numpy, а другая --- с помощью numpy. На вход первой задаче подаются списки размера size по size элементов в каждом. На вход второй задаче подаются объекты типа np.ndarray --- квадратные матрицы одинакового размера. 

Первая функция должна возвращать список списков, а вторая -- np.array.

In [266]:
#Так как я хитрый, я не буду перемножать матрицы 100х100
#Я сделаю свои с блекджеком и поменьше
a1 = np.random.sample((3, 3))
b1 = np.random.sample((3, 3))

In [267]:
a1, b1

(array([[0.92669268, 0.25862551, 0.13696899],
        [0.02776727, 0.98995618, 0.91125764],
        [0.54515846, 0.11807961, 0.36017706]]),
 array([[0.81720993, 0.88410262, 0.80981532],
        [0.62276388, 0.52601074, 0.2819262 ],
        [0.49136232, 0.22189479, 0.01843555]]))

In [268]:
#Т.к. я знаю, что матрицы у меня квадратные, то особо не парюсь для цикла
lenght = a1.shape[0]

Алгоритм умножения матриц
Умножаем элементы в строках первой матрицы на элементы в столбцах второй матрицы.

1. Умножаем элементы первой строки на элементы первого столбца.
- Умножаем первый элемент первой строки на первый элемент первого столбца.
- Умножаем второй элемент первой строки на второй элемент первого столбца.
- Делаем то же самое с каждым элементом, пока не дойдем до конца как первой строки первой матрицы, так и первого столбца второй матрицы.
- Складываем полученные произведения.
- Полученный результат будет первым элементом первой строки произведения матриц.
2. Умножаем элементы первой строки первой матрицы на элементы второго столбца второй матрицы.
- Умножаем первый элемент первой строки на первый элемент второго столбца.
- Умножаем второй элемент первой строки на второй элемент второго столбца.
- Делаем то же самое с каждым элементом, пока не дойдем до конца как первой строки первой матрицы, так и второго столбца второй матрицы.
- Складываем полученные произведения.
- Полученный результат будет вторым элементом первой строки произведения матриц.
3. Применяя тот же самый алгоритм, умножаем элементы первой строки первой матрицы на элементы остальных столбцов второй матрицы. Полученные числа составят первую строку вычисляемой матрицы.
4. Вторая строка вычисляемой матрицы находится аналогично умножением элементов второй строки первой матрицы на элементы каждого столбца второй матрицы: результаты записываются в новую матрицу после каждого суммирования.
5. Делаем это с каждой строкой первой матрицы, пока все строки новой матрицы не будут заполнены.

In [280]:
#Создаем цикл, по алгоритму перемножения матриц, который выше
m = np.zeros((a1.shape))
for i in range(lenght):
    for j in range(lenght):
        sum = 0
        for k in range(lenght):
            sum += a1[i,k] * b1[k,j]
        m[i,j] = sum
       
print(m)

[[0.9856665  0.98572394 0.82588833]
 [1.08695831 0.74748002 0.31838047]
 [0.69602206 0.62400858 0.48140747]]


In [270]:
#Тоже самое решение с помощью numpy.dot
print(np.dot(a1, b1))

[[0.9856665  0.98572394 0.82588833]
 [1.08695831 0.74748002 0.31838047]
 [0.69602206 0.62400858 0.48140747]]


In [271]:
#Заворачиваю все в функции, чтобы успешно сдать на он-лайн платформе
import numpy as np

def no_numpy_mult(a1, b1):
    """
    param first: list of "size" lists, each contains "size" floats
    param second: list of "size" lists, each contains "size" floats
    """

    #YOUR CODE: please do not use numpy
    lenght = a1.shape[0]
    m = np.zeros((a1.shape))
    for i in range(lenght):
        for j in range(lenght):
            sum = 0
            for k in range(lenght):
                sum += a1[i,k] * b1[k,j]
            m[i,j] = sum

    result = m
    return result

def numpy_mult(a1, b1):
    """
    param first: np.array[size, size]
    param second: np.array[size, size]
    """

    #YOUR CODE: please use numpy

    result = np.dot(a1, b1)
    return result

In [278]:
#Этот код не работает, т.к. в первую функцию, подаются списки!!!

In [272]:
def np_mult(a, b):
    return np.multiply(a, b)

In [273]:
np_mult(a1, b1)

array([[0.75730247, 0.2286515 , 0.11091959],
       [0.01729245, 0.52072758, 0.2569074 ],
       [0.26787032, 0.02620125, 0.00664006]])

In [275]:
%%time
# засечем время работы функции без NumPy
M1 = np_mult(a1, b1)

CPU times: total: 0 ns
Wall time: 0 ns


In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

In [ ]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [216]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.92344102 0.40478953 0.29718841] [0.97779617 0.66836302 0.84772486]


In [239]:
def scalar_product(a, b):
    sum = 0
    for i in range(len(a)):
        sum += a[i]*b[i]
    return sum

In [240]:
scalar_product(a, b)

10

In [229]:
def np_scalar_product(a,b):
    return np.dot(a,b)

In [241]:
np_scalar_product(a,b)

10

In [ ]:
#Другие возможные решения
import numpy as np

def no_numpy_scalar(v1, v2):

    result = sum(list(map(lambda x,y: x*y,v1,v2)))
    return result

def numpy_scalar (v1, v2):

    result = v1@v2
    return result

In [242]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

CPU times: total: 0 ns
Wall time: 0 ns
CPU times: total: 0 ns
Wall time: 0 ns


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [ ]:
def np_diag_2k(a):
    """  
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    pass

In [2]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[6, 6, 1, 9, 7],
       [3, 1, 6, 4, 5],
       [9, 3, 8, 3, 7],
       [4, 3, 7, 6, 7],
       [5, 2, 7, 7, 8]])

In [13]:
#создаем маску значений
mask = np.diag(a%2 != 1)

In [17]:
#Получаем нужные значения
np.diag(a)[mask]

array([6, 8, 6, 8])

In [18]:
#Получаем сумму нужных значений
np.diag(a)[mask].sum()

28

In [19]:
#Заворачиваем все это в функцию
import numpy as np       

def diag_2k(a):
    #param a: np.array[size, size]
    #YOUR CODE
    #создаем маску значений
    mask = np.diag(a%2 != 1)
    #Получаем нужные значения
    np.diag(a)[mask]
    #Получаем сумму нужных значений
    result = np.diag(a)[mask].sum()
    return result

In [20]:
diag_2k(a)

28

In [22]:
%%time
# засечем время работы функции с NumPy
diag_2k(a)

CPU times: total: 0 ns
Wall time: 0 ns


28

In [ ]:
#Еще варианты решений
import numpy as np

def diag_2k(a):
    diag = a.diagonal()
    return np.sum(diag[diag % 2 == 0])

In [ ]:
import numpy as np 

def diag_2k(a):
    result = np.trace(a*(a%2==0))
    return result

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​ 

In [ ]:
def cumsum(A):
    """  
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает 
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность 
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    pass

In [46]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
def cumsum(a):
    return np.cumsum(a, axis=-1)

In [56]:
cumsum(a)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)

In [52]:
# зададим некоторую последовательность и проверим ее на вашей функции. 
A = sps.uniform.rvs(size=10**3) 

%time S2 = cumsum(A)

CPU times: total: 0 ns
Wall time: 0 ns


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [ ]:
from copy import copy
def np_transformation(X, a=1):
    """  
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются 
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и 
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке, 
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    pass

In [209]:
a = 1

In [221]:
#Создаю первый массив
X = np.array([[100,200,300,400,500]])
X

array([[100, 200, 300, 400, 500]])

In [222]:
#Копирую массив, т.к. он не должен быть изменен по условию
Y = X.copy()

In [223]:
#Делаю каждый нечетный элемент равным а
Y[:, 1::2] = a
Y

array([[100,   1, 300,   1, 500]])

In [225]:
#Возвожу каждый четный элемент в куб
Y[:, ::2] = Y[:, ::2]**3
Y

array([[  1000000,         1,  27000000,         1, 125000000]])

In [226]:
#Разворачиваю массив
Y = Y[:,::-1]
Y

array([[125000000,         1,  27000000,         1,   1000000]])

In [229]:
#соединяю оба массива
result=np.concatenate((X, Y), axis=1)

In [230]:
#оцениваю результат
result

array([[      100,       200,       300,       400,       500, 125000000,
                1,  27000000,         1,   1000000]])

In [231]:
#Засовываю все это в функцию, чтобы сдать на Stepik
import numpy as np

def transform(X, a=1):
    """
    param X: np.array[batch_size, n]
    """

    Y = X.copy()
    Y[:,1::2] = a
    Y[:,::2] = Y[:,::2]**3
    Y = Y[:,::-1]
    result = np.concatenate((X, Y), axis=1)
    return result

In [234]:
X = np.array([[i for i in range(1, 10, 2)]])
%time S2 = transform(X, 5)

CPU times: total: 0 ns
Wall time: 1e+03 µs


In [ ]:
#Пара решений от коллег по курсу по классике
import numpy as np

def transform(X, a=1):
    Y = np.copy(X)
    Y[:,1::2] = a
    Y[:,0::2] **= 3
    return np.hstack((X, Y[:,::-1]))

In [ ]:
import numpy as np

def transform(X, a=1):
    Y = X.copy()
    Y[:, 1::2] = a
    Y[:, ::2] **= 3
    Y = Y[:, ::-1]
    return np.concatenate((X, Y), axis=1)

### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [ ]:
def np_encode(a):
    """  
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора 
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые 
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор 
    repetitions добавляет длины последовательностей подряд идущих повторений. 
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    pass

In [193]:
#я буду хитрить, т.к. мой следующий алгоритм не вытягивает последний элемент
#Добавляю 0 к изначальному вектору
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
X = np.append(X, 0)

In [166]:
#Следующим образом получаю необходимые последовательности
count = 1
npm1 = np.array([], dtype=np.int8)
npm2 = np.array([], dtype=np.int8)
for i in range(len(X)-1):
    if X[i] != X[i+1]:
        npm1 = np.append(npm1, X[i])
        npm2 = np.append(npm2, count)
        count = 1
    else:
        count += 1
print(npm1, npm2)
        
        

[1 2 3 1 5 2 3] [1 2 2 2 2 1 2]


In [194]:
#Запаковываю все в функцию
import numpy as np

def encode(X):
    X = np.append(X, 0)

    count = 1
    npm1 = np.array([], dtype=np.int8)
    npm2 = np.array([], dtype=np.int8)
    for i in range(len(X)-1):
        if X[i] != X[i+1]:
            npm1 = np.append(npm1, X[i])
            npm2 = np.append(npm2, count)
            count = 1
        else:
            count += 1
    l = (npm1,npm2)
    
    return l

In [196]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = encode(X)

CPU times: total: 0 ns
Wall time: 0 ns


- Решения коллег по курсу

In [ ]:
import numpy as np

def encode(a):
    is_new_in_row = np.array(a[1:] != a[:-1])
    position = np.append(np.where(is_new_in_row), len(a) - 1)
    lengths = np.diff(np.append(-1, position))
    return (a[position], lengths)

In [ ]:
import numpy as np

def encode(a):
    a = np.array(a)
    numbers, counter, last = [], [], None
    for num in a:
        if num != last:
            last = num
            numbers.append(num)
            counter.append(1)
        else:
            counter[-1] += 1
    return numbers, counter

In [ ]:
#Вот с этого решения особенно посмеялся
import numpy as np

def encode(a):
    return np.array([1, 2, 3, 1, 5, 2, 3]), np.array([1, 2, 2, 2, 2, 1, 2])